alias cp='cp -v'
alias grep='grep --color=auto'
alias vimrc='vim ~/.vimrc'
alias numfiles='ls -1 | wc -l'
alias ll='ls -lAvh --color --group-directories-first'
alias ls='ls -hA --color --group-directories-first'
alias cenv='source activate'
alias deactivate='source deactivate'
alias workon='source activate'
